#[Info]
site_name: 0X10CC's notes #your site name æ˜¾ç¤ºåœ¨å·¦ä¸Šè§’
site_url: https://tang-jiapeng.github.io/
site_author: 0X10CC # your name
#[UI]
theme:
  name: material
  
  custom_dir: docs/overrides #è¦†å†™è·¯å¾„
  # font: #è°·æ­Œå­—ä½“ï¼Œè‡ªè¡Œæœç´¢
  #   text: Roboto   #æ–‡æœ¬å­—ä½“
  #   code: Roboto Mono  #ä»£ç å­—ä½“
  logo: assets/logo.ico #å·¦ä¸Šè§’logoï¼Œå¯æ’å…¥å›¾ç‰‡é“¾æ¥

  favicon: assets/logo.ico # ç½‘é¡µicon

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: å…³é—­è‡ªåŠ¨æ¨¡å¼
    #primary: blue grey
    - media: "(prefers-color-scheme: light)"
      scheme: default # æ—¥é—´æ¨¡å¼
      primary: blue grey # ä¸Šæ–¹çš„
      accent: blue # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      # teal
      toggle:
        icon: material/toggle-switch # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # å¤œé—´æ¨¡å¼
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼

  features:
    - announce.dismiss #å‘ˆç°å¯æ ‡è®°ä¸ºç”±ç”¨æˆ·è¯»å–çš„ä¸´æ—¶å…¬å‘Šï¼Œå¯ä»¥åŒ…å«ä¸€ä¸ªç”¨äºå–æ¶ˆå½“å‰å…¬å‘Šçš„æŒ‰é’®
    # - navigation.instant
    #- header.autohide  #è‡ªåŠ¨éšè—
    - navigation.tracking #åœ°å€æ ä¸­çš„ URL å°†è‡ªåŠ¨æ›´æ–°ä¸ºåœ¨ç›®å½•ä¸­çªå‡ºæ˜¾ç¤ºçš„æ´»åŠ¨é”šç‚¹
    - navigation.tabs #é¡¶çº§éƒ¨åˆ†å°†å‘ˆç°åœ¨ä¸Šé¢è§†å£æ ‡é¢˜ä¸‹æ–¹çš„èœå•å±‚ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    # - navigation.tabs.sticky  #å¯ç”¨ç²˜æ€§é€‰é¡¹å¡åï¼Œå¯¼èˆªé€‰é¡¹å¡å°†é”å®šåœ¨æ ‡é¢˜ä¸‹æ–¹ï¼Œå¹¶åœ¨å‘ä¸‹æ»šåŠ¨æ—¶å§‹ç»ˆä¿æŒå¯è§
    - navigation.sections #å¯ç”¨éƒ¨åˆ†åï¼Œé¡¶çº§éƒ¨åˆ†åœ¨è¾¹æ ä¸­å‘ˆç°ä¸º1220pxä»¥ä¸Šè§†å£çš„ç»„ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - navigation.footer #é¡µè„šå°†å‘ˆç°åœ¨è¾¹æ ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - search.share #æœç´¢åˆ†äº«æŒ‰é’®
    - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - navigation.indexes #å¯ç”¨èŠ‚ç´¢å¼•é¡µåï¼Œå¯ä»¥å°†æ–‡æ¡£ç›´æ¥é™„åŠ åˆ°èŠ‚
    - content.tabs.link
    - content.tooltips
    - content.code.copy #ä»£ç å¤åˆ¶
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - toc.follow
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡

  icon:
    repo: fontawesome/brands/github #å³ä¸Šè§’å›¾æ ‡
    logo: logo
edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥
repo_url: https://github.com/tang-jiapeng/tang-jiapeng.github.io # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: tang-jiapeng.github.io # å³ä¸Šè§’çš„åå­—

# [Navigtion]
nav:
  # - ğŸ¡ä¸»é¡µ: index.md

  - ç¼–ç¨‹è¯­è¨€:
      - langs/index.md
      # - Golangæ‚è®°:
          # - 
      - C++é›¶ç¢æ‚è®°:
          - é¡¶å±‚constä¸åº•å±‚const: langs/cpp/é›¶ç¢æ‚è®°/é¡¶å±‚constä¸åº•å±‚const.md
          - å€¼ç±»å‹ä¸å³å€¼å¼•ç”¨: langs/cpp/é›¶ç¢æ‚è®°/å€¼ç±»å‹ä¸å³å€¼å¼•ç”¨.md
          - æ•°ç»„æŒ‡é’ˆä¸å‡½æ•°æŒ‡é’ˆ: langs/cpp/é›¶ç¢æ‚è®°/æ•°ç»„æŒ‡é’ˆä¸å‡½æ•°æŒ‡é’ˆ.md
          - C++ç±»å¯¹è±¡å¸ƒå±€: langs/cpp/é›¶ç¢æ‚è®°/C++ç±»å¯¹è±¡å¸ƒå±€.md
          - C++ä¸­çš„å¤šæ€ä¸RTTI: langs/cpp/é›¶ç¢æ‚è®°/C++ä¸­çš„å¤šæ€ä¸RTTI.md
      - Effective Modern C++:
          - item1ï¼šç†è§£æ¨¡æ¿ç±»å‹æ¨å¯¼: langs/cpp/effective/item1.md
          - item2ï¼šç†è§£autoç±»å‹æ¨å¯¼: langs/cpp/effective/item2.md
          - item3ï¼šç†è§£decltype: langs/cpp/effective/item3.md
          - item7ï¼šåŒºåˆ«ä½¿ç”¨()å’Œ{}åˆ›å»ºå¯¹è±¡: langs/cpp/effective/item7.md
          - item9ï¼šä¼˜å…ˆè€ƒè™‘åˆ«åå£°æ˜è€Œétypedef: langs/cpp/effective/item9.md
          - item23ï¼šç†è§£std::moveå’Œstd::forward: langs/cpp/effective/item23.md
  - è®¡ç®—æœºåŸºç¡€:
      - core/csapp/index.md
      - CSAPPé˜…è¯»ç¬”è®°:
          - Chapter1ï¼šè®¡ç®—æœºç³»ç»Ÿæ¼«æ¸¸: core/csapp/ch1.md
          - Chapter2ï¼šä¿¡æ¯çš„è¡¨ç¤ºå’Œå¤„ç†: core/csapp/ch2.md
          - Chapter3ï¼šç¨‹åºçš„æœºå™¨çº§è¡¨ç¤º: core/csapp/ch3.md
          # - Chapter4ï¼šå¤„ç†å™¨ä½“ç³»ç»“æ„: core/csapp/ch4.md
          # - Chapter5ï¼šä¼˜åŒ–ç¨‹åºæ€§èƒ½: core/csapp/ch5.md
          - Chapter6ï¼šå­˜å‚¨å™¨å±‚æ¬¡ç»“æ„: core/csapp/ch6.md
          - Chapter7ï¼šé“¾æ¥: core/csapp/ch7.md
          - Chapter8ï¼šå¼‚å¸¸æ§åˆ¶æµ: core/csapp/ch8.md
          - Chapter9ï¼šè™šæ‹Ÿå†…å­˜: core/csapp/ch9.md
          - Chapter10ï¼šç³»ç»Ÿçº§I/O: core/csapp/ch10.md
          - Chapter11ï¼šç½‘ç»œç¼–ç¨‹: core/csapp/ch11.md
          - Chapter12ï¼šå¹¶å‘ç¼–ç¨‹: core/csapp/ch12.md
  
  - åˆ†å¸ƒå¼ç³»ç»Ÿ:
      - core/distributed/index.md
      - MapReduce: core/distributed/MapReduce.md
      - Paxos: core/distributed/Paxos.md

  - åç«¯å¼€å‘:
      - develop/index.md
      - Goè¯­è¨€è¿›é˜¶ä¸ä¾èµ–ç®¡ç†: develop/ByteDance/02.md
      - Goè¯­è¨€å·¥ç¨‹å®è·µä¹‹æµ‹è¯•: develop/ByteDance/03.md

  - å·¥å…·:
      - tools/index.md
      - Git: tools/git.md

  # - æ ‡ç­¾: tag.md
  # - ç•™è¨€æ¿: liuyanban.md
  # - Blogger:
  #     - index: blog/index.md
  # - å‹é“¾:
  #     - å‹é“¾: about/link.md
  # - å…³äº:
  #     - ä½œè€…ä¸ªäººç®€ä»‹: about/geren.md
  #     - åŠŸèƒ½æµ‹è¯•: about/test.md
  # - ä½¿ç”¨æœ¬ä¸»é¢˜: https://github.com/new?template_name=Mkdocs-Wcowin&template_owner=Wcowin

copyright: Copyright &copy; 2022~2024 0X10CC/All Rights Reserved. # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜

extra:
  # alternate:
  #   - name: ç®€ä½“ä¸­æ–‡
  #     link: /
  #     # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
  #     lang: zh   
    # - name: English
    #   link: /Mkdocs-Wcowin/en/
    #   # https://wcowin-work.translate.goog/?_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp
    #   lang: en
    # - name: China(TW)
    #   link: /Mkdocs-Wcowin/ZH-TW/
    #   # https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
    #   lang: zh-TW
  generator: true #æ˜¯å¦åˆ é™¤é¡µè„šæ˜¾ç¤ºâ€œä½¿ç”¨ MkDocs ææ–™åˆ¶é€ â€
  social:
    # - icon: fontawesome/brands/x-twitter #è”ç³»æ–¹å¼å›¾æ ‡ : https://fontawesome.com/ å»è¿™é‡Œæ‰¾å›¾æ ‡
    #   link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/tang-jiapeng

    - icon: fontawesome/regular/envelope #è”ç³»æ–¹å¼å›¾æ ‡
      link: mailto:<tangjiapeng0215@gmail.com> #é‚®ä»¶è”ç³»æ–¹å¼
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
  analytics:
    provider: google #è°·æ­Œåˆ†æ
    property:

    # ç½‘é¡µåº•éƒ¨åé¦ˆ
    # feedback:
    #   title: æ­¤é¡µé¢æœ‰å¸®åŠ©å—ï¼Ÿ
    #   ratings:
    #     - icon: material/thumb-up-outline #å›¾æ ‡å¯è‡ªå®šä¹‰
    #       name: This page was helpful
    #       data: 1
    #       note: >-
    #         è°¢è°¢ä½ çš„åé¦ˆï¼
    #     - icon: material/thumb-down-outline
    #       name: This page could be improved
    #       data: 0
    #       note: >-
    #         Thanks for your feedback! Help us improve this page by
    #         using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  # cookiesè®¾ç½®ï¼ˆå¯é€‰ï¼‰
  # consent:
  #   title: Cookie consent
  #   description: >-
  #     æˆ‘ä»¬ä¹Ÿä½¿ç”¨cookiesæ¥è¯†åˆ«æ‚¨çš„é‡å¤è®¿é—®å’Œåå¥½æ¥è¡¡é‡æˆ‘ä»¬æ–‡æ¡£çš„æœ‰æ•ˆæ€§ä»¥åŠç”¨æˆ·æ˜¯å¦æ‰¾åˆ°ä»–ä»¬è¦æ‰¾çš„ä¸œè¥¿ã€‚
  #     å¦‚æœä½ åŒæ„,ä½ å¯ä»¥å¸®åŠ©æˆ‘ä»¬è®©æˆ‘ä»¬çš„ç½‘ç«™æ›´å¥½

plugins:
  - search #æœç´¢é…ç½®
  - git-committers:
      enabled: !ENV [CI, false]
      repository: tang-jiapeng/tang-jiapeng.github.io
      branch: master
      exclude:
        - index.md
        # - tag.md
        # - waline.md
        # - blog/posts/update.md
        # - blog/posts/wkw.md
        # - about/link.md
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: iso_date
      enable_creation_date: true
      exclude:
        - index.md
        # - tag.md
        # - liuyanban.md
        # - blog/posts/update.md
        # - blog/posts/wkw.md
        # - about/link.md
        # - websitebeauty/linktech.md
  # - blog: #åšå®¢é…ç½®
  #     post_date_format: full #æ—¶é—´
  #     draft: true
  #     draft_if_future_date: true #è‡ªåŠ¨å°†å…·æœ‰æœªæ¥æ—¥æœŸçš„å¸–å­æ ‡è®°ä¸ºè‰ç¨¿
  #     post_readtime: true
  #     post_readtime_words_per_minute: 265 #è®¡ç®—å¸–å­çš„é˜…è¯»æ—¶é—´æ—¶è¯»è€…æ¯åˆ†é’Ÿé¢„è®¡é˜…è¯»çš„å­—æ•°
  #     post_url_format: "{date}/{slug}"
      # categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
      #   kwds:
      #     case: lower
      # pagination_url_format: "page/{page}"
      # authors_file: "{blog}/.authors.yml" #ä½œè€…ä¿¡æ¯
  # - tags:
  #     tags_file: tag.md #åˆ†ç±»æ ‡ç­¾

markdown_extensions: #è¯¦è§https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/ å’Œ https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  # - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # ä»£ç å—é«˜äº®æ’ä»¶
  - pymdownx.arithmatex: # latexæ”¯æŒ
      generic: true
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      linenums: true # æ˜¾ç¤ºè¡Œå·
      # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  # - markdown.extensions.toc:
  #     slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
  #     permalink: "\ue157"

extra_javascript:
  # - "from_oi_wiki/js/extra.js"
  # - javascripts/extra.js #è‡ªå®šä¹‰javascript
  - https://cdn.jsdelivr.net/gh/Wcowin/Wcowin.github.io@main/docs/javascripts/extra.js  # extraçš„cdn
  - javascripts/mathjax.js #Latexæ”¯æŒ
  - https://polyfill.io/v3/polyfill.min.js?features=es6 #Latexæ”¯æŒ
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js #Latexæ”¯æŒ
  # - ckplayer/js/ckplayer.js #æ’­æ”¾å™¨é…ç½®
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalkæ”¯æŒ
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js #å¿˜äº†

extra_css:
  - stylesheets/extra.css # è‡ªå®šä¹‰CSS
  - stylesheets/link.css #å‹é“¾é…ç½®
  - stylesheets/customize.css # æœç´¢åœ†è§’ä¼˜åŒ–

  # - stylesheets/video.css #æ’­æ”¾å™¨å¯é€‰é…ç½®
  # - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalkæ”¯æŒ
  # - ckplayer/css/ckplayer.css   #æ’­æ”¾å™¨é…ç½®
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css # font-awesomeè¡¨æƒ…æ”¯æŒ
  # - https://cdnjs.cloudflare.com/ajax/libs/social-share.js/1.0.16/css/share.min.css  #åˆ†äº«æ”¯æŒ
  - https://cdn.jsdelivr.net/npm/fontsource-noto-serif-sc@4.0.0/index.min.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css #å­—ä½“
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css #å­—ä½“
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css  #å­—ä½“
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css  #å­—ä½“
  # - "from_oi_wiki/css/extra.css?v=13"
  # - css/status.css
  # - css/neoteroi-mkdocs.css
